### ISSUE TITLE
Ability to split SwaggerBase by referencing other files

### ISSUE THREAD

**Issue by bgk-** [readmeio/swagger-inline#13]
Perhaps I missed this, but it would be great if in the `swaggerBase.yaml` it was possible to reference other yaml files to be combined into one for the output. Right now the swagger base can get very large with all the components.

Something like
`./swaggerBase.yaml`
```
components:
  schemas:
    $ref: 'path/to/schemas.yaml'
```
`./path/to/schemas.yaml`
```
User:
  description: 'User'
  properties:
    id:
      type: string
    email:
      type: string
```

and the final output would be the combined files
```
components:
  schemas:
    User:
      description: 'User'
      properties:
        id:
          type: string
        email:
          type: string
```

Or even to take it further be able to nest them so within the `path/to/schemas.yaml` you could have another `$ref` to a subfolder with further yamls. This would split up the single large file to more manageable chunks.
